// Using subcategories for more granular organization
export const CATEGORIES = [
  // Produce subcategories
  'produce_fruits',
  'produce_vegetables',
  'produce_herbs',
  'produce_packaged_salads',
  'produce_cut_prepared',
  // Meat & Seafood subcategories
  'meat_beef',
  'meat_pork',
  'meat_poultry',
  'meat_lamb',
  'meat_processed',
  'meat_halal',
  'seafood_fresh',
  'seafood_shellfish',
  'seafood_frozen',
  // Dairy & Eggs subcategories
  'dairy_milk_cream',
  'dairy_ayran',
  'dairy_eggs_sub',
  'dairy_cheese_turkish',
  'dairy_cheese_international',
  'dairy_yogurt',
  'dairy_butter',
  'dairy_alternatives',
  // Bakery subcategories
  'bakery_bread',
  'bakery_turkish_bread',
  'bakery_simit',
  'bakery_flatbreads',
  'bakery_pastries',
  'bakery_cakes_pies',
  // Deli & Prepared subcategories
  'deli_sliced_meats',
  'deli_sliced_cheese',
  'deli_meze',
  'deli_salads',
  'deli_ready_meals',
  'deli_sushi',
  // Frozen subcategories
  'frozen_meals',
  'frozen_pizza',
  'frozen_vegetables',
  'frozen_fruit',
  'frozen_dessert',
  'frozen_bakery',
  // Pantry subcategories
  'pantry_pasta',
  'pantry_rice',
  'pantry_bulgur',
  'pantry_canned_veg',
  'pantry_canned_tomatoes',
  'pantry_canned_legumes',
  'pantry_canned_olive',
  'pantry_canned_meat_fish',
  'pantry_oils',
  'pantry_vinegars',
  'pantry_flour',
  'pantry_sugar_sweeteners',
  'pantry_spices',
  'pantry_cereal',
  'pantry_oats',
  'pantry_spreads_sweet',
  'pantry_chocolate_spreads',
  'pantry_ketchup_mustard_mayo',
  'pantry_hot_sauces',
  'pantry_salad_dressings',
  'pantry_pasta_sauce',
  'pantry_turkish',
  'pantry_middle_eastern',
  'pantry_american',
  'pantry_asian',
  'pantry_european',
  // Snacks & Candy subcategories
  'snacks_chips',
  'snacks_crackers',
  'snacks_nuts_seeds',
  'snacks_bars',
  'snacks_cookies',
  'snacks_candy_chocolate',
  'snacks_turkish_delight',
  'snacks_dried_fruit',
  // Beverages subcategories
  'bev_water',
  'bev_soda',
  'bev_juice',
  'bev_energy_sports',
  'bev_tea_turkish',
  'bev_tea_other',
  'bev_coffee_turkish',
  'bev_coffee_ground',
  'bev_coffee_instant',
  'bev_milk_shelf_stable',
  // Alcohol subcategories
  'alcohol_beer',
  'alcohol_wine',
  'alcohol_raki',
  'alcohol_spirits',
  // Household subcategories
  'household_cleaning',
  'household_laundry',
  'household_dishwashing',
  'household_paper',
  'household_trash_storage',
  'household_air_care',
  // Health & Personal Care subcategories
  'health_otc',
  'health_vitamins',
  'personal_oral',
  'personal_hair',
  'personal_body',
  'personal_deodorant',
  'personal_shaving',
  'personal_feminine',
  // Baby & Kids subcategories
  'baby_diapers',
  'baby_wipes',
  'baby_food',
  'baby_care',
  // Pet subcategories
  'pet_dog',
  'pet_cat',
  'pet_other',
  'Other'
] as const;

export type Category = typeof CATEGORIES[number];
